### PR TITLE
Reject unsupported glibc in installer

### LINKED ISSUE #544: Wrong glibc version after installing using cli.
I ran `curl -fsSL https://install.microsandbox.dev | sh`

but when I try to use it:

```bash
➜ msb --help
msb: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by msb)
msb: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.39' not found (required by msb)
```

Shouldn't the installer detect stuff like that?

### PR DESCRIPTION
**Pull request by qaijuang**
Fixes #544

---
<a href="https://app.blacksmith.sh/superradcompany/codesmith/microsandbox/pr/635"><picture><source media="(prefers-color-scheme: dark)" srcset="https://pr-comments-assets.blacksmith.sh/codesmith/view-in-codesmith-dark.svg"><source media="(prefers-color-scheme: light)" srcset="https://pr-comments-assets.blacksmith.sh/codesmith/view-in-codesmith-light.svg">View in Codesmith</picture></a>
<sup>Need help on this PR? Tag <code>@codesmith</code> with what you need.</sup>

- [ ] Let Codesmith autofix CI failures and bot reviews

### CODE REVIEW

File: scripts/install.sh [hunk 1]
```diff
@@ -324,6 +328,65 @@ detect_platform() {
...
+
+verify_linux_compatibility() {
+    _glibc_version=$(detect_glibc_version || true)
+    if [ -z "$_glibc_version" ]; then
+        error "microsandbox Linux releases currently require glibc >= ${LINUX_GLIBC_MIN_VERSION}; could not detect a supported glibc runtime on this system"
+    fi
+
+    if glibc_version_lt "$_glibc_version" "$LINUX_GLIBC_MIN_VERSION"; then
+        error "microsandbox Linux releases currently require glibc >= ${LINUX_GLIBC_MIN_VERSION}; detected ${_glibc_version}"
+    fi
```
Comment (toksdotdev) [inline scripts/install.sh:389]: nit: 

```suggestion
    _glibc_requirement="Microsandbox Linux releases require glibc ${LINUX_GLIBC_MIN_VERSION} or newer"

    if [ -z "$_glibc_version" ]; then
        error "${_glibc_requirement}, but a compatible glibc runtime was not detected. Please use a glibc-based Linux environment."
    fi

    if glibc_version_lt "$_glibc_version" "$LINUX_GLIBC_MIN_VERSION"; then
        error "${_glibc_requirement}, but this system has glibc ${_glibc_version}. Please use a newer glibc-based Linux environment."
    fi
```

File: scripts/install.sh [hunk 2]
```diff
@@ -324,6 +328,65 @@ detect_platform() {
...
+    if [ "$_lhs_major" -lt "$_rhs_major" ]; then
+        return 0
+    fi
+    if [ "$_lhs_major" -gt "$_rhs_major" ]; then
+        return 1
+    fi
+    [ "$_lhs_minor" -lt "$_rhs_minor" ]
+}
+
+verify_linux_compatibility() {
```
Comment (toksdotdev) [inline scripts/install.sh]:
```suggestion
check_linux_compatibility() {
```

**Review by toksdotdev — COMMENTED** [review]
asides the comments, lgtm!

File: scripts/install.sh [hunk 3]
```diff
@@ -364,6 +429,10 @@ main() {
     detect_platform
     info "Detected platform: $TARGET"
 
+    if [ "$OS" = "linux" ]; then
+        verify_linux_compatibility
```
Comment (toksdotdev) [inline scripts/install.sh]:
```suggestion
        check_linux_compatibility
```

**Review by toksdotdev — APPROVED** [review]
